language: python
dist: focal

before_install:
  # Install conda
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels conda-forge
install:
  - conda create -n test python=$TRAVIS_PYTHON_VERSION isa-l tox
  - source activate test

python: 3.6  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    # TEST DOCS AND LINTING
    # Use default python3 version here.
    - env: TOX_ENV=docs
    - env: TOX_ENV=lint
    # UNIT TESTS
    # On most recent versions of python.
    - env: TOX_ENV=py36
      after_success:
        - pip install codecov
        - codecov -v  # -v to make sure coverage upload works.
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
